"""The nineteen re-export shims left at the old assurance paths, checked against the rule.

Design brief §11 T11 moved the assurance family from `rig_workbench/workbench/` to
`rig_workbench/assurance/` and left a shim at each old path so that an importer has one
major to change the word in. A bridge like that fails in a way nothing else notices: it
is written once by hand, the module it mirrors keeps changing, and the first sign that a
name stopped resolving is somebody else's ImportError after the shim was deleted. There
is no other check — `ruff` sees a valid import, the type checker sees a valid import, and
every test in this repository reads the *new* path, because they were all moved in the
same commit. So the drift has to be re-derived here, from the live modules, on every run.

The rule the shims are generated by, stated in `rig_workbench/assurance/__init__.py`:
**every name the moved module exposes that is neither a dunder nor an imported module
object.** Not "the public ones" — `import *` is exactly the shape that drops underscore
names, and seventeen of these files were missing names their module defines while it was
in use. Not "the ones somebody currently imports" either: the bridge exists for callers
outside this repository, and what they import cannot be measured from inside it.

`test_the_rule_is_not_vacuous` is the one that keeps the rest honest. A checker written
backwards — comparing a module against itself, or comparing two empty sets — passes every
assertion below, so the corpus asserts that the rule *rejects* a shim with a name removed
and one with an extra name, using modules built here rather than the ones under test.
"""

from __future__ import annotations

import importlib
import sys
import types

import pytest

#: The nineteen modules that moved. Named rather than globbed: a glob would silently
#: shrink to nothing if the package were renamed, and this file would keep passing.
MOVED = (
    "anomaly_trigger", "assurance", "assurance_budget", "assurance_target",
    "assurance_wiring", "change_graph", "compose_options", "contract",
    "development_loop", "import_task", "intent", "intent_wiring",
    "knowledge_candidate", "org_knowledge", "production_outcome",
    "provenance_graph", "synthesis", "team_routing", "workflow_effectiveness",
)

NEW_PACKAGE = "rig_workbench.assurance"
OLD_PACKAGE = "rig_workbench.workbench"

#: This is the one module in the tree that imports the bridge on purpose, so it is the one
#: module that must not be failed by the warning the bridge raises. Everything else runs
#: clean under `-W error::DeprecationWarning`, which is how "nothing in-tree reaches the old
#: path" is measured rather than claimed. The filter does not weaken
#: `test_importing_the_old_path_warns_...`: `pytest.warns` installs its own `always` filter
#: for the length of the block.
pytestmark = pytest.mark.filterwarnings("ignore::DeprecationWarning")

#: The major the shims go in. Written here as well as in each docstring so that moving
#: the sunset means editing a literal a test reads, not nineteen sentences nobody greps.
SUNSET = "4.0.0"


def bridged_names(module: types.ModuleType) -> set[str]:
    """The rule: everything the module exposes but dunders and imported modules."""
    return {
        name for name in dir(module)
        if not name.startswith("__")
        and not isinstance(getattr(module, name), types.ModuleType)
    }


@pytest.mark.parametrize("name", MOVED)
def test_the_old_path_still_imports(name: str) -> None:
    """The bridge's whole purpose, asserted before anything is read off it."""
    assert importlib.import_module(f"{OLD_PACKAGE}.{name}") is not None


@pytest.mark.parametrize("name", MOVED)
def test_every_public_name_of_the_new_module_is_on_the_shim(name: str) -> None:
    """`dir()` minus underscores, both sides, equal — not merely a subset.

    A subset check would pass a shim that had grown names the module no longer has,
    which is the same stale list read from the other direction.
    """
    new = importlib.import_module(f"{NEW_PACKAGE}.{name}")
    old = importlib.import_module(f"{OLD_PACKAGE}.{name}")
    public = {n for n in bridged_names(new) if not n.startswith("_")}
    bridged = {n for n in bridged_names(old) if not n.startswith("_")}
    assert bridged == public, (
        f"{OLD_PACKAGE}.{name} no longer mirrors {NEW_PACKAGE}.{name}.\n"
        f"  missing from the shim: {sorted(public - bridged) or 'none'}\n"
        f"  on the shim and not the module: {sorted(bridged - public) or 'none'}\n"
        "Regenerate the shim's import list from the rule in "
        "rig_workbench/assurance/__init__.py, or delete the bridge if 4.0.0 has landed."
    )


@pytest.mark.parametrize("name", MOVED)
def test_the_private_names_are_bridged_too_because_import_star_would_drop_them(
    name: str,
) -> None:
    """The half `import *` cannot do, and the reason these lists are written out."""
    new = importlib.import_module(f"{NEW_PACKAGE}.{name}")
    old = importlib.import_module(f"{OLD_PACKAGE}.{name}")
    private = {n for n in bridged_names(new) if n.startswith("_")}
    assert private <= bridged_names(old), (
        f"{OLD_PACKAGE}.{name} drops {sorted(private - bridged_names(old))}. "
        "Underscore names are in the rule on purpose: they are what `import *` loses."
    )


@pytest.mark.parametrize("name", MOVED)
def test_importing_the_old_path_warns_with_the_new_path_and_the_removal_major(
    name: str,
) -> None:
    """A docstring is only read by somebody already looking at the file.

    The failure this warns about is silent: a downstream
    `monkeypatch.setattr("rig_workbench.workbench.assurance.build_receipt", …)` still
    succeeds and simply does not land, because the function that reads the name resolves
    it in the new module's globals. An import-time `DeprecationWarning` is what makes
    that findable from a test run rather than from the changelog.

    The module is dropped from `sys.modules` first: a warning fires once per import, and
    every other test in this file has already imported all nineteen.
    """
    old_path = f"{OLD_PACKAGE}.{name}"
    sys.modules.pop(old_path, None)
    with pytest.warns(DeprecationWarning) as caught:
        importlib.import_module(old_path)
    messages = [str(w.message) for w in caught]
    assert any(f"{NEW_PACKAGE}.{name}" in m and SUNSET in m for m in messages), (
        f"{old_path} imported without a DeprecationWarning naming "
        f"{NEW_PACKAGE}.{name} and {SUNSET}. Got: {messages}"
    )


@pytest.mark.parametrize("name", MOVED)
def test_the_shim_says_when_it_goes(name: str) -> None:
    """A sunset nobody can find is a bridge that becomes permanent by default."""
    doc = importlib.import_module(f"{OLD_PACKAGE}.{name}").__doc__ or ""
    assert SUNSET in doc, (
        f"{OLD_PACKAGE}.{name}'s docstring does not name {SUNSET}. The removal major is "
        "the only thing telling a reader this file is temporary."
    )


def test_the_package_docstring_states_the_rule_the_shims_are_generated_by() -> None:
    """The rule lives in one place; this fails if that paragraph is edited away."""
    doc = importlib.import_module(NEW_PACKAGE).__doc__ or ""
    assert "dunder" in doc and "imported module" in doc and SUNSET in doc


def test_the_bridged_total_in_the_package_docstring_is_the_measured_one() -> None:
    """A figure written in prose rots silently; this one cannot.

    `assurance/__init__.py` says the claim is "about all N names" rather than about the
    public ones, which is the sentence that makes the rule worth having. If a module
    gains or loses a name the shims are regenerated and that N moves, so the number is
    read back out of the docstring and compared against the walk.
    """
    measured = sum(
        len(bridged_names(importlib.import_module(f"{NEW_PACKAGE}.{name}")))
        for name in MOVED
    )
    doc = importlib.import_module(NEW_PACKAGE).__doc__ or ""
    assert f"all {measured} names" in doc, (
        f"the bridge now carries {measured} names; "
        "update the figure in rig_workbench/assurance/__init__.py to match."
    )


def test_the_rule_is_not_vacuous() -> None:
    """Built here, not imported: the rule must reject both directions of drift."""
    complete = types.ModuleType("complete")
    complete.PUBLIC, complete._private = 1, 2
    complete.a_module = importlib
    short = types.ModuleType("short")
    short.PUBLIC = 1
    extra = types.ModuleType("extra")
    extra.PUBLIC, extra._private, extra.GONE = 1, 2, 3

    assert bridged_names(complete) == {"PUBLIC", "_private"}, "module objects must drop out"
    assert bridged_names(short) != bridged_names(complete), "a dropped private must show"
    assert bridged_names(extra) != bridged_names(complete), "an extra name must show"
    assert "__name__" not in bridged_names(complete), "dunders must drop out"
