"""The 51 `rig-wb wb` capabilities, declared once (v3 stage 2).

Derived from `rig_workbench/workbench/cli.py`, which registers all of them against a single
`add_subparsers` object: 51 `add_parser` calls, 51 distinct names, no nested subparser
anywhere in the file — so the stage-1 caution about call sites inflating the count does not
bite here, and the two numbers agree.

Four things are declared that argparse never asked anybody to write, and they are the ones
`docs/v3-architecture-design-brief.ja.md` §9 puts above the CLI: `intent` (what the person
wanted), `preconditions` (what a machine can check first), `effect_line` (the sentence shown
immediately before it runs) and the two independent `effect_class` / `network` axes. The
rest — flags, output schema, exit codes — is read back off the parsers, the handlers, and
the two test files that measured them:

* `tests/test_schema_cli_contract.py` pinned which command emits which `rig.<name>/v<N>`
  through real CLI runs, so `output_schema` follows what a process printed rather than what
  a constant is named. Among this slice only `wb gates` goes through `jsonio.envelope`;
  every other `--json` here prints an ad-hoc object with no id, and those declare `None`.
* `tests/test_exit_code_surface.py` measured the codes through a subprocess. `state.die()`
  is 2 and `state.reject()` is 1 after the correction, and in this whole slice only
  `accept` reaches `reject()` — every other 1 below is a sensor or a judgement command
  exiting on its own finding, and every 2 is `die()` or an `EXECUTION_ERROR` constant.

Declaration only: no handler, no callable, nothing imported from `rig_workbench.workbench`.
Wiring the surfaces onto this table is stage 3, and each `preconditions` name becomes one
checker there.
"""

from __future__ import annotations

from .model import Capability, ExitCode, Flag

#: `workbench/config.py`'s `TASK_TYPES` keys, written out rather than imported: importing
#: that module would pull the workbench package into a leaf, and the choice list is part of
#: the observable command surface anyway. Kept in the order that file declares them.
_TASK_TYPES = (
    "bugfix", "feature", "refactor", "test", "performance", "documentation", "design",
    "investigation", "release_support", "review", "security_review",
)

#: `route_cli.add_context_arguments`, which `new` and `route` both call. Declared once here
#: for the same reason it is a helper there: two copies drift.
_ROUTE_CONTEXT = (
    Flag(name="--recipe", type="string", help="name one recipe explicitly instead of letting rig route"),
    Flag(name="--remote-pr", type="bool", help="route this as a review of a remote pull request"),
    Flag(name="--has-diff", type="bool", help="a local or caller-supplied diff is already available"),
    Flag(name="--diff", type="string", help="a path to a diff, or the diff text itself"),
    Flag(name="--read-only", type="bool", help="route without an implementation worktree"),
    Flag(name="--implementation-type", type="choice", choices=("feature", "bugfix"),
         help="for test work, which implementation route the tests are written against"),
)

#: `die()` reached this command: nothing was judged.
_ERROR = ExitCode(code=2, meaning="rig could not answer — bad usage, missing task, unreadable state")

#: The three-way answer every document-judging command in this slice returns.
_JUDGED = (
    ExitCode(code=0, meaning="rig read the document and everything it checks holds"),
    ExitCode(code=1, meaning="rig read the document and something it checks does not hold"),
    ExitCode(code=2, meaning="rig could not read or reach the document at all"),
)


WB_CAPABILITIES: tuple[Capability, ...] = (
    # ── the lifecycle ────────────────────────────────────────────────────────
    Capability(
        id="wb.new",
        parent="wb",
        verb="new",
        intent="start a piece of work somewhere it cannot damage what is already here",
        preconditions=("git-repo", "task-type-known", "recipe-resolvable", "worktree-runtime-available"),
        effect_line="worktree と branch を新しく作り、.rig/runs 配下に run 記録を作ります（--agent を渡したときは、その worktree で agent セッションを起動し、task package を渡します）",
        effect_class="writes-worktree",
        network="sometimes",
        flags=(
            Flag(name="input", type="string", required=True, help="the task in the person's own words"),
            Flag(name="--type", type="string", required=True, help=f"task type: {', '.join(_TASK_TYPES)}"),
            Flag(name="--slug", type="string", help="short English slug for the task id (derived from the input if omitted)"),
            Flag(name="--base", type="string", help="base branch to measure against (defaults to the current branch)"),
            *_ROUTE_CONTEXT,
            Flag(name="--reason", type="string", help="why this recipe was chosen, for the banner and the log"),
            Flag(name="--no-worktree", type="bool", help="skip worktree creation, for read-only runs such as review"),
            Flag(name="--runtime", type="choice", choices=("auto", "native", "orca"), default="auto",
                 help="which worktree runtime to use; an explicit orca never downgrades silently"),
            Flag(name="--agent", type="string", help="start this agent in a fresh session inside the new worktree (Orca runtime only)"),
            Flag(name="--budget-minutes", type="float", help="estimated minutes; flagged when exceeded, never enforced"),
            Flag(name="--caller", type="string", help="name the harness invoking rig, recorded on the task"),
            Flag(name="--issue", type="string", help="the issue this run is against (#123 or owner/repo#123)"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the task is registered and its worktree exists"), _ERROR),
    ),
    Capability(
        id="wb.import",
        parent="wb",
        verb="import",
        intent="put a change somebody else's tool produced through the same checks as rig's own work",
        preconditions=("git-repo", "task-type-known", "head-commit-exists", "recipe-resolvable",
                       "worktree-runtime-available"),
        effect_line="指定した commit を base から切り出した worktree と branch に取り込み、外部 producer の申告つきで run 記録を作ります（申告は記録するだけで、gate には一切効きません）",
        effect_class="writes-worktree",
        network="never",
        flags=(
            Flag(name="--head", type="string", required=True, help="the change to verify; a commit SHA cannot move and is preferred"),
            Flag(name="--base", type="string", help="base branch the change is measured against"),
            Flag(name="--type", type="string", required=True, help=f"task type: {', '.join(_TASK_TYPES)}"),
            Flag(name="--producer", type="string", required=True, help="who produced the change; recorded as a declaration, never verified"),
            Flag(name="--producer-runtime", type="string", help="the runtime or model the producer ran on, if stated"),
            Flag(name="--producer-run-id", type="string", help="the producer's own run identifier, kept as provenance"),
            Flag(name="--producer-url", type="string", help="a link back to the producing run, kept as provenance"),
            Flag(name="--producer-claim", type="string-list", help="NAME=VALUE the producer reports about its own work; never part of the verdict"),
            Flag(name="--summary", type="path", help="an authored diff summary; without it rig derives one and labels it derived"),
            Flag(name="--input", type="string", help="the task description; defaults to the imported commit's subject"),
            Flag(name="--slug", type="string", help="short English slug for the task id"),
            Flag(name="--reason", type="string", help="why this recipe was chosen, for the banner and the log"),
            Flag(name="--budget-minutes", type="float", help="estimated minutes; flagged when exceeded, never enforced"),
            Flag(name="--caller", type="string", help="name the harness invoking rig, recorded on the task"),
            Flag(name="--runtime", type="choice", choices=("auto", "native", "orca"), default="auto",
                 help="which worktree runtime to use; an explicit orca never downgrades silently"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the external change is registered as an ordinary task"), _ERROR),
    ),
    Capability(
        id="wb.step",
        parent="wb",
        verb="step",
        intent="say how far along the work is, so a later session can pick it up without guessing",
        preconditions=("git-repo", "task-exists"),
        effect_line="run 記録の steps.json を、渡された STEP=STATUS のとおりに書き換えます",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--set", type="string-list", required=True,
                 help="STEP=STATUS, one of pending / running / passed / failed / skipped (repeatable)"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the step record is updated"), _ERROR),
    ),
    Capability(
        id="wb.gate",
        parent="wb",
        verb="gate",
        intent="check whether the work is finished enough to hand over, and hear what is still missing",
        preconditions=("git-repo", "task-exists"),
        effect_line="acceptance.json に採点を書き込み、まだ pending の criteria を一覧します",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--set", type="string-list",
                 help="CRITERION=STATUS[:DETAIL], status one of pending / passed / failed / warning / skipped (repeatable)"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="the gate is not in a failed state"),
            ExitCode(code=1, meaning="rig judged the criteria and the gate is failed"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.diff",
        parent="wb",
        verb="diff",
        intent="see what this run actually changed, before deciding anything about it",
        preconditions=("git-repo", "task-exists", "task-has-worktree"),
        effect_line="base commit との差分をまとめて表示します。ファイルには何も書きません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the diff is shown"), _ERROR),
    ),
    Capability(
        id="wb.accept",
        parent="wb",
        verb="accept",
        intent="bring this work back into the real tree now that it has been judged good enough",
        preconditions=("git-repo", "task-exists", "task-not-closed", "task-has-worktree",
                       "base-branch-recorded", "diff-summary-written", "worktree-clean",
                       "main-tree-clean", "branch-ahead-of-base"),
        effect_line="task branch を今の working tree に squash merge して staged のまま残します（commit はしません）。task を accepted にし、署名つき provenance.json を書きます。worktree と branch はここでは消えません",
        effect_class="writes-worktree",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--force", type="bool",
                 help="apply despite an unmet gate; recorded in the audit log, and structural preconditions still refuse"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="the change is staged in the main working tree"),
            ExitCode(code=1, meaning="rig judged and refused — an unmet gate, an actor without permission, or governance"),
            ExitCode(code=2, meaning="rig could not apply it — no worktree, a dirty tree, or a conflicting squash merge"),
        ),
    ),
    Capability(
        id="wb.discard",
        parent="wb",
        verb="discard",
        intent="throw this attempt away and get the workspace back, keeping the record that it happened",
        preconditions=("git-repo", "explicit-task-id", "task-exists", "worktree-runtime-available"),
        effect_line="worktree と branch を削除し、visual/ の一時画像も消します。.rig/runs の run 記録は残ります。worktree の未コミット変更はここで失われます",
        effect_class="writes-worktree",
        network="never",
        flags=(
            Flag(name="task_id", type="string", required=True,
                 help="the task; required outright, because discarding the wrong one cannot be undone"),
            Flag(name="--yes", type="bool", help="confirm the deletion after seeing what will be lost"),
            Flag(name="--local-cleanup", type="bool",
                 help="remove the checkout with git when its owning runtime is unusable here, and record that"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the worktree and branch are gone and the run log is kept"), _ERROR),
    ),
    Capability(
        id="wb.status",
        parent="wb",
        verb="status",
        intent="find out where one piece of work stands right now and what it is waiting on",
        preconditions=("git-repo", "task-exists"),
        effect_line="その task の状態・steps・gate の記録を読み上げます。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the state is shown"), _ERROR),
    ),
    Capability(
        id="wb.board",
        parent="wb",
        verb="board",
        intent="see everything in flight at once, when several runs are going and none of them is the only one",
        preconditions=("git-repo",),
        effect_line="進行中の task を一覧表示します（--all で accepted / discarded も含めます）。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="--all", type="bool", help="include tasks that are already accepted or discarded"),),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the board is shown"), _ERROR),
    ),
    Capability(
        id="wb.log",
        parent="wb",
        verb="log",
        intent="look back at what has been run here recently, to find the one worth reopening",
        preconditions=("git-repo",),
        effect_line="過去の run 記録を新しい順に一覧します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="--limit", type="int", default=10, help="how many runs to list"),
            Flag(name="--json", type="bool", help="emit the listing as JSON"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the log is shown"), _ERROR),
    ),
    Capability(
        id="wb.cockpit",
        parent="wb",
        verb="cockpit",
        intent="get the whole situation on one screen instead of running five commands and joining them by eye",
        preconditions=("git-repo",),
        effect_line="board / gate / drill / cost / audit を 1 画面にまとめて表示します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the aggregated view is shown"), _ERROR),
    ),

    # ── the deterministic sensors ────────────────────────────────────────────
    Capability(
        id="wb.scan-secrets",
        parent="wb",
        verb="scan-secrets",
        intent="make sure nothing that should have stayed private is about to be committed",
        preconditions=("scan-target-readable",),
        effect_line="指定した範囲を読んで秘密情報らしき箇所を報告します（値は必ずマスクします）。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="paths", type="string-list", help="files or directories to scan; defaults to the current directory"),
            Flag(name="--diff", type="string", help="scan only that task worktree's diff against its base commit"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="nothing that looks like a secret was found"),
            ExitCode(code=1, meaning="rig found something that looks like a secret, and printed it masked"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.scan-injection",
        parent="wb",
        verb="scan-injection",
        intent="find text that is written to steer whatever model reads it next, rather than to be read",
        preconditions=("scan-target-readable",),
        effect_line="prose 面を読んで、不可視 Unicode（fail 相当）と指示上書き文言（warning 相当）を報告します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="paths", type="string-list", help="files or directories to scan; defaults to the repo's prose surfaces"),
            Flag(name="--diff", type="string", help="scan that task's diff plus its prose surfaces, which is what the gate sensor sees"),
            Flag(name="--deps", type="bool", help="also scan dependency trees' prose files; opt-in, never part of the default surfaces"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="no fail-grade injection marker was found"),
            ExitCode(code=1, meaning="rig found a fail-grade injection marker"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.scan-destructive",
        parent="wb",
        verb="scan-destructive",
        intent="catch a command that would wipe something out before anybody runs it by accident",
        preconditions=("scan-target-readable",),
        effect_line="rm -rf / mkfs / dd / DROP DATABASE などの破壊的コマンドを探して報告します。何も実行も書き換えもしません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="paths", type="string-list", help="files or directories to scan; defaults to the current directory"),
            Flag(name="--diff", type="string", help="scan only that task worktree's diff against its base commit"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="no fail-grade destructive command was found"),
            ExitCode(code=1, meaning="rig found a fail-grade destructive command"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.scan-anchors",
        parent="wb",
        verb="scan-anchors",
        intent="check that a reviewer's citations point at code that is really there, not at plausible line numbers",
        preconditions=("scan-target-readable",),
        effect_line="reviewer の本文にある `file.py:42` 形式の引用が実在する行を指しているか照合します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="paths", type="string-list", help="reviewer body files, or directories whose *.md are bodies"),
            Flag(name="--diff", type="string", help="scan the bodies recorded for that task, which is what the gate sensor sees"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="every cited anchor resolves"),
            ExitCode(code=1, meaning="rig found a citation that points at a line that is not there"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.scan-ja-prose",
        parent="wb",
        verb="scan-ja-prose",
        intent="find the Japanese this run added that reads badly, before a reviewer has to say so",
        preconditions=("git-repo", "task-exists", "base-commit-recorded"),
        effect_line="diff で追加された日本語の行だけを textlint 相当のルールで検査して報告します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="task_id", type="string", help="the task; defaults to the most recent one"),),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="the added Japanese has no error-grade finding"),
            ExitCode(code=1, meaning="rig found error-grade findings in the added Japanese"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.stream-checks",
        parent="wb",
        verb="stream-checks",
        intent="get told about a problem while the work is still going, instead of at the gate",
        preconditions=("git-repo", "task-exists", "base-commit-recorded"),
        effect_line="秘密情報・injection・破壊的コマンド・引用アンカーの軽量センサーをヒントとして流します。gate は一切止めず、何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--watch", type="bool", help="keep polling and re-scan when the diff or a recorded review body changes"),
            Flag(name="--interval", type="float", default=5.0, help="seconds between polls, with --watch"),
            Flag(name="--max-passes", type="int", help="stop after this many passes, with --watch; unbounded by default"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the hints are printed; this sensor never blocks"), _ERROR),
    ),
    Capability(
        id="wb.stale-refs",
        parent="wb",
        verb="stale-refs",
        intent="find the places where the written instructions still point at a file that has moved or gone",
        preconditions=("scan-target-readable",),
        effect_line="manifest と knowledge のバッククォート付き相対パスが実在するか照合し、WARN として報告します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="paths", type="string-list",
                    help="files or directories to scan; defaults to the manifest plus project knowledge"),),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="reported as warnings; this check never fails a run"),),
    ),

    # ── the assurance surface ────────────────────────────────────────────────
    Capability(
        id="wb.receipt",
        parent="wb",
        verb="receipt",
        intent="get one portable file that shows everything that was checked on this change, to hand to someone outside",
        preconditions=("git-repo", "task-exists"),
        effect_line="記録済みの gate / provenance / approvals を投影して .rig/runs/<task>/assurance.json と assurance.md を書き出します。新しい判定はしません",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--json", type="bool", help="print the receipt as JSON"),
            Flag(name="--markdown", type="bool", help="print the human-readable rendering"),
            Flag(name="--verify", type="bool", help="check an existing receipt still matches the files it projected"),
        ),
        output_schema="rig.assurance-receipt/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the receipt is built, or with --verify it is still fresh"),
            ExitCode(code=1, meaning="with --verify: the receipt is stale — what it projected has changed since"),
            _ERROR,
        ),
    ),
    Capability(
        id="wb.contract",
        parent="wb",
        verb="contract",
        intent="get the single yes / no / not-yet a script can branch on, without reading the whole record",
        preconditions=("git-repo", "task-exists"),
        effect_line="receipt を作り直して書き出したうえで、acceptable / not-acceptable / pending / execution-error のいずれか 1 語と、それに対応する終了コードを返します",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--json", type="bool", help="emit the contract document as JSON"),
        ),
        output_schema="rig.assurance-contract/v1",
        exit_codes=(
            ExitCode(code=0, meaning="acceptable"),
            ExitCode(code=1, meaning="not acceptable — rig looked and the answer is no"),
            ExitCode(code=2, meaning="execution error — rig could not reach an answer at all"),
            ExitCode(code=3, meaning="pending — nothing has been judged yet, so ask again later"),
        ),
    ),
    Capability(
        id="wb.intent",
        parent="wb",
        verb="intent",
        intent="find out where what we wrote down as required is still too vague for anything to check",
        preconditions=("intent-contract-readable",),
        effect_line="渡された intent contract を検証し、検査されていない点・宣言されていない点を一覧します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="file", type="path", required=True, help="a rig.intent-contract/v1 JSON document"),
            Flag(name="--json", type="bool", help="emit the summary as JSON"),
        ),
        output_schema="rig.intent-contract/v1",
        exit_codes=_JUDGED,
    ),
    Capability(
        id="wb.intent-derive",
        parent="wb",
        verb="intent-derive",
        intent="work out what our written requirements oblige us to do, and which of it nothing here provides",
        preconditions=("intent-contract-readable", "derivation-basis-readable"),
        effect_line="requirements から、--floor なら踏まねばならない steps を、--target なら求められている assurance target を導き、届いていない分を並べます。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="file", type="path", required=True, help="a rig.intent-contract/v1 JSON document"),
            Flag(name="--against", type="path", required=True,
                 help="the component catalog for --floor, or the gate's criteria for --target, as a JSON array"),
            Flag(name="--floor", type="bool", help="derive the steps the requirements put on a workflow's floor"),
            Flag(name="--target", type="bool", help="derive the assurance target the requirements ask for"),
            Flag(name="--json", type="bool", help="emit the result as JSON"),
        ),
        output_schema="rig.intent-contract/v1",
        exit_codes=_JUDGED,
    ),
    Capability(
        id="wb.assurance-target",
        parent="wb",
        verb="assurance-target",
        intent="find out whether a finished run really reached the level of assurance we said it needed",
        preconditions=("git-repo", "task-exists", "assurance-target-readable"),
        effect_line="求めた target と、その run の receipt が実際に記録した内容を軸ごとに突き合わせます。足りない軸を黙って通すことはしません。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="task_id", type="string", required=True, help="the run whose receipt is being held to the target"),
            Flag(name="target", type="path", required=True, help="a rig.assurance-target/v1 JSON document"),
            Flag(name="--json", type="bool", help="emit the comparison as JSON"),
        ),
        output_schema="rig.assurance-target/v1",
        exit_codes=(
            ExitCode(code=0, meaning="every axis the target asked for was reached"),
            ExitCode(code=1, meaning="an axis is unmet or unobservable, so the assurance is incomplete"),
            ExitCode(code=2, meaning="the target or the run's record could not be read"),
        ),
    ),
    Capability(
        id="wb.assurance-derive",
        parent="wb",
        verb="assurance-derive",
        intent="turn a level of assurance we have already decided on into the steps that would actually reach it",
        preconditions=("assurance-target-readable", "axis-requirements-readable", "component-catalog-readable"),
        effect_line="宣言された「どの軸のどの値にどの step が要るか」の対応から、その target に必要な workflow floor を導きます。対応のない軸値は飛ばさず拒否します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="target", type="path", required=True, help="a rig.assurance-target/v1 JSON document"),
            Flag(name="--requires", type="path", required=True,
                 help="a JSON object {axis: {value: [{id, source, reason}, ...]}} saying which steps reach each outcome"),
            Flag(name="--against", type="path", required=True, help="the component catalog, as a JSON array"),
            Flag(name="--json", type="bool", help="emit the result as JSON"),
        ),
        output_schema="rig.assurance-target/v1",
        exit_codes=_JUDGED,
    ),

    # ── the judgement commands ───────────────────────────────────────────────
    Capability(
        id="wb.knowledge-candidate",
        parent="wb",
        verb="knowledge-candidate",
        intent="check that something somebody wants written down as a lesson is really supported by what happened",
        preconditions=("git-repo", "knowledge-candidate-readable", "cited-evidence-readable"),
        effect_line="候補が引用する記録を一つずつ読み、主張が実際に裏づけられているかを報告します。--register / --promote を渡したときだけ .rig/org-knowledge.jsonl に 1 行追記します",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="candidate", type="path", help="a rig.knowledge-candidate/v1 JSON document"),
            Flag(name="--json", type="bool", help="emit the assessment as JSON"),
            Flag(name="--register", type="bool", help="enter a supported candidate into the lifecycle at `candidate`"),
            Flag(name="--promote", type="string", help="move the registered record with this id one step along"),
            Flag(name="--to", type="string", help="the next state: evaluated, approved, active, deprecated or rolled_back"),
            Flag(name="--actor", type="string", help="who is approving; required from `approved` on, and never inferred"),
            Flag(name="--reason", type="string", help="why; required from `approved` on"),
            Flag(name="--list", type="bool", help="every registered record with its current state"),
            Flag(name="--state", type="string", help="filter the listing by state"),
            Flag(name="--history", type="string", help="one record's full path through the ledger"),
            Flag(name="--active", type="bool", help="only the active rules, with their citations, as a consumer reads them"),
        ),
        output_schema="rig.knowledge-candidate-assessment/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the cited records explicitly support the candidate"),
            ExitCode(code=1, meaning="rig read the citations and they do not support it"),
            ExitCode(code=2, meaning="the candidate or its evidence could not be read, so nothing is observable"),
        ),
    ),
    Capability(
        id="wb.change-graph",
        parent="wb",
        verb="change-graph",
        intent="find out whether a set of changes spread over several repositories can be landed in any order at all",
        preconditions=("change-graph-readable",),
        effect_line="宣言された依存関係のもとで実行順序が成り立つかを判定し、成り立たないなら詰まっている箇所を示します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="graph", type="path", required=True, help="a rig.change-graph/v1 JSON document"),
            Flag(name="--json", type="bool", help="emit the assessment as JSON"),
        ),
        output_schema="rig.change-graph-assessment/v1",
        exit_codes=(
            ExitCode(code=0, meaning="an execution order exists under the declared dependencies"),
            ExitCode(code=1, meaning="no execution order exists"),
            ExitCode(code=2, meaning="the graph could not be read, so the order is unobservable"),
        ),
    ),
    Capability(
        id="wb.anomaly-trigger",
        parent="wb",
        verb="anomaly-trigger",
        intent="decide whether something that went wrong in production has enough behind it to start digging",
        preconditions=("anomaly-event-readable", "cited-evidence-readable"),
        effect_line="外部から渡された異常イベントが、調査を始めるだけの裏づけを宣言できているかを判定します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="event", type="path", required=True, help="a rig.production-anomaly-event/v1 JSON document"),
            Flag(name="--json", type="bool", help="emit the assessment as JSON"),
        ),
        output_schema="rig.production-anomaly-trigger-assessment/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the event carries enough supported material to start an investigation"),
            ExitCode(code=1, meaning="the event does not carry enough"),
            ExitCode(code=2, meaning="the event or its evidence could not be read"),
        ),
    ),
    Capability(
        id="wb.synthesise",
        parent="wb",
        verb="synthesise",
        intent="check that a plan somebody proposed uses steps that exist and has not quietly dropped a mandatory one",
        preconditions=("resolved-workflow-readable", "component-catalog-readable"),
        effect_line="提案された workflow を component catalog と、planner が削ってはならない policy floor に照らして検証します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="workflow", type="path", required=True, help="a rig.resolved-workflow/v1 JSON document"),
            Flag(name="catalog", type="path", required=True, help="a JSON array of registered component ids"),
            Flag(name="--required", type="path",
                 help="a JSON object mapping a mandatory step id to why it is required, and who requires it"),
            Flag(name="--json", type="bool", help="emit the resolution report as JSON"),
        ),
        output_schema="rig.workflow-resolution/v1",
        exit_codes=(
            ExitCode(code=0, meaning="every step exists and the floor held"),
            ExitCode(code=1, meaning="the workflow is refused — an unknown step, or a floor step that was dropped"),
            ExitCode(code=2, meaning="the workflow or the catalog could not be read"),
        ),
    ),
    Capability(
        id="wb.dev-loop",
        parent="wb",
        verb="dev-loop",
        intent="find out whether an agent that ran on its own stopped when it should have, and whether what it handed back is backed by the record",
        preconditions=("git-repo", "task-exists", "development-cycles-readable"),
        effect_line="記録された各周回を、宣言した停止条件（周回数・同一失敗の連続・進捗なしの連続）と receipt に照らして判定します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="task", type="string", help="the task; defaults to the one currently active"),
            Flag(name="cycles", type="path", required=True, help="a rig.development-cycles/v1 JSON document"),
            Flag(name="--max-cycles", type="int", help="how many cycles before the loop must stop"),
            Flag(name="--repeated-failure", type="int", help="consecutive identical failures before the loop must stop"),
            Flag(name="--no-progress", type="int", help="consecutive cycles ending with the same product before it must stop"),
            Flag(name="--json", type="bool", help="emit the handoff judgement as JSON"),
        ),
        output_schema="rig.development-cycles/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the loop stayed within its bounds and the handoff is admissible"),
            ExitCode(code=1, meaning="the loop overran a bound, or the handoff is not backed by the receipt"),
            ExitCode(code=2, meaning="the cycles record could not be read"),
        ),
    ),
    Capability(
        id="wb.route-team",
        parent="wb",
        verb="route-team",
        intent="check that the people or agents put on this change are actually allowed to hold the roles they were given",
        preconditions=("team-routing-readable", "routing-constraints-readable"),
        effect_line="誰がどの assurance role に就いたかを、policy が述べる identity / 承認 / 能力 / 独立性の制約に照らして検査します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="routing", type="path", required=True, help="a rig.team-routing/v1 JSON document"),
            Flag(name="--constraints", type="path", required=True,
                 help="a JSON object with 'identity' and optionally approved, capable, measured, also_independent, required and task"),
            Flag(name="--json", type="bool", help="emit the check as JSON"),
        ),
        output_schema="rig.team-routing/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the routing satisfies every hard constraint"),
            ExitCode(code=1, meaning="the routing breaks a hard constraint"),
            ExitCode(code=2, meaning="the routing or its constraints could not be read"),
        ),
    ),
    Capability(
        id="wb.budget-plan",
        parent="wb",
        verb="budget-plan",
        intent="pick the cheapest way of working that still clears the bar we are not allowed to go under",
        preconditions=("assurance-budget-readable", "budget-constraints-readable"),
        effect_line="候補の計画のうち assurance floor を満たすものだけを残し、宣言された予算と最適化方針に沿って 1 つ選びます。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="plans", type="path", required=True, help="a rig.assurance-budget/v1 JSON document"),
            Flag(name="--budget", type="path", required=True,
                 help="a JSON object stating required and task, and optionally max_cost, max_latency_seconds, optimisation and seconds_per_unit_cost"),
            Flag(name="--json", type="bool", help="emit the choice as JSON"),
        ),
        output_schema="rig.assurance-budget/v1",
        exit_codes=(
            ExitCode(code=0, meaning="a plan was chosen"),
            ExitCode(code=1, meaning="no candidate clears the floor within the budget"),
            ExitCode(code=2, meaning="the plans or the budget could not be read"),
        ),
    ),
    Capability(
        id="wb.provenance",
        parent="wb",
        verb="provenance",
        intent="find out why something in the record exists and what is actually holding it up",
        preconditions=("provenance-graph-readable", "node-in-graph"),
        effect_line="指定した node から辺をたどり、確認済みの関係と推測にすぎない関係を分けたまま示します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="graph", type="path", required=True, help="a rig.provenance-graph/v1 JSON document"),
            Flag(name="node", type="string", required=True, help="the node id to trace from"),
            Flag(name="--direction", type="choice", choices=("up", "down", "both"), default="both",
                 help="follow edges out of the node, into it, or both"),
            Flag(name="--no-resolve", type="bool",
                 help="do not look up whether each confirmed authority exists; the answer then says so"),
            Flag(name="--json", type="bool", help="emit the trace as JSON"),
        ),
        output_schema="rig.provenance-graph/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the node was traced"),
            ExitCode(code=1, meaning="the node cannot be traced — it is absent, or nothing reaches it"),
            ExitCode(code=2, meaning="the graph could not be read"),
        ),
    ),
    Capability(
        id="wb.expected-outcome",
        parent="wb",
        verb="expected-outcome",
        intent="find out whether the change did in production what we said it would, by the number we said it by",
        preconditions=("expected-outcome-readable", "production-observation-readable", "as-of-timestamp-valid"),
        effect_line="宣言した指標を baseline / target / 観測窓に照らして判定します。--task を渡したときだけ、その run の下に比較結果を書き込みます",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="expected", type="path", required=True, help="a rig.expected-outcome/v1 JSON document"),
            Flag(name="--observed", type="path", required=True,
                 help="a rig.production-observation/v1 document; it states values only, never targets"),
            Flag(name="--as-of", type="string", required=True,
                 help="ISO 8601 timestamp with an offset saying when the window is judged; required, never defaulted to now"),
            Flag(name="--task", type="string", help="cross-check the change against that run's receipt and record the comparison there"),
            Flag(name="--json", type="bool", help="emit the comparison as JSON"),
        ),
        output_schema="rig.production-outcome/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the expectation was met and the window has closed"),
            ExitCode(code=1, meaning="the expectation was not met, or the window is still open"),
            ExitCode(code=2, meaning="the expectation or the observation could not be read"),
        ),
    ),
    Capability(
        id="wb.effectiveness",
        parent="wb",
        verb="effectiveness",
        intent="find out which kinds of failure keep coming back here, from what was actually recorded rather than from impressions",
        preconditions=("git-repo", "effectiveness-query-readable"),
        effect_line="閉じた query の範囲だけで、記録済みの workflow 指標と再発パターンを集計します。記録にないことは推測せず、何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="--query", type="path", required=True,
                 help="a closed JSON query defining the recurrence, lateness and repair limits"),
            Flag(name="--json", type="bool", help="emit the report as JSON"),
        ),
        output_schema="rig.workflow-effectiveness/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the metrics were derived within the query's bounds"),
            ExitCode(code=1, meaning="the query is refused — it asks for something the records cannot bound"),
            ExitCode(code=2, meaning="the query could not be read"),
        ),
    ),

    # ── the operational ones ─────────────────────────────────────────────────
    Capability(
        id="wb.route",
        parent="wb",
        verb="route",
        intent="find out which way of working rig would pick for this, before committing to it",
        preconditions=("git-repo", "task-type-known", "recipe-resolvable"),
        effect_line="`new` が選ぶのと同じ解決を、同じ tree に対して実行して結果だけ表示します。install も worktree 作成も記録も行いません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="--type", type="string", required=True, help=f"task type: {', '.join(_TASK_TYPES)}"),
            *_ROUTE_CONTEXT,
            Flag(name="--json", type="bool", help="emit the exact route record"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="a recipe resolved and rig would act on it"),
            ExitCode(code=2, meaning="nothing was routed — resolution failed, or rig declined to act on the winner"),
        ),
    ),
    Capability(
        id="wb.compose-options",
        parent="wb",
        verb="compose-options",
        intent="see the choices worth offering for this kind of work, without being asked to invent them on the spot",
        preconditions=("task-type-known",),
        effect_line="task type と差分規模から、対話的な組み立てのための 5 つの選択軸を決定的に導きます。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="--type", type="choice", required=True, choices=_TASK_TYPES, help="the classified task type"),
            Flag(name="--diff", type="int", help="non-negative added plus removed lines; omit when unobservable"),
            Flag(name="--json", type="bool", help="emit the options document as JSON"),
        ),
        output_schema="rig.compose-options/v1",
        exit_codes=(
            ExitCode(code=0, meaning="the five axes are derived"),
            ExitCode(code=2, meaning="the arguments could not be used — an unknown type, or a negative diff size"),
        ),
    ),
    Capability(
        id="wb.gc",
        parent="wb",
        verb="gc",
        intent="reclaim the space taken by verification screenshots nobody is going to look at again",
        preconditions=("git-repo",),
        effect_line="一定日数を過ぎた visual/ の一時画像ディレクトリを削除します（--dry-run なら候補を並べるだけ）。ソース・worktree・branch には触りません",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="--older-than", type="string", help="remove items older than this many days, as <N>d; default 14d"),
            Flag(name="--dry-run", type="bool", help="only list the candidates, deleting nothing"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the old images are gone, or listed under --dry-run"), _ERROR),
    ),
    Capability(
        id="wb.audit",
        parent="wb",
        verb="audit",
        intent="see who overrode a check here and when, when somebody asks how that got in",
        preconditions=("git-repo",),
        effect_line=".rig/audit.jsonl の記録（`accept --force` など）を新しい順に一覧します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="--limit", type="int", help="show only the latest N entries"),
            Flag(name="--action", type="string", help="filter by action name, for example accept_force"),
            Flag(name="--since", type="string", help="show only entries since YYYY-MM-DD"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the audit entries are shown"), _ERROR),
    ),
    Capability(
        id="wb.digest",
        parent="wb",
        verb="digest",
        intent="get something readable to circulate about how the last week or month went here",
        preconditions=("git-repo",),
        effect_line="直近 7 日か 30 日の runs / gates / force-accept / rubber-stamp / drill を Markdown にまとめます。--out を渡したときだけ、その path にファイルを書き出します",
        effect_class="writes-worktree",
        network="never",
        flags=(
            Flag(name="--period", type="choice", choices=("week", "month"), default="week",
                 help="rolling window: week is the last 7 days, month the last 30"),
            Flag(name="--out", type="path", help="write the Markdown to this file instead of stdout"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the digest is produced"), _ERROR),
    ),
    Capability(
        id="wb.stats",
        parent="wb",
        verb="stats",
        intent="find out whether a way of working or a particular reviewer is really earning its place",
        preconditions=("git-repo",),
        effect_line="過去の run を recipe 別・gate 別に集計し、素通しに見える verifier を検出して表示します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(
            Flag(name="--recipe", type="string", help="filter by recipe name"),
            Flag(name="--verifier", type="string", help="filter by persona name; only runs recorded in review.json"),
            Flag(name="--last", type="string", help="restrict to the last N days, for example 30d"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the aggregate is shown"), _ERROR),
    ),
    Capability(
        id="wb.instincts",
        parent="wb",
        verb="instincts",
        intent="keep hold of something learned the hard way, so the next session does not learn it again",
        preconditions=("git-repo",),
        effect_line="学習された instinct を一覧・追加・muted / expired 化し、--promote / --demote では repo と ~/.rig の間で 1 件だけ移します。--generate-checks は .rig/recipes/<name>.md に checks を書き足します",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="--add", type="string", help="record an instinct candidate, at most 300 characters"),
            Flag(name="--evidence", type="string", help="with --add: a short explanation of why this is believed"),
            Flag(name="--task-id", type="string", help="with --add: the task this candidate came from"),
            Flag(name="--confidence", type="float", default=0.5, help="with --add: initial confidence"),
            Flag(name="--supersedes", type="string", help="with --add: mute this id and replace it with the new one"),
            Flag(name="--mute", type="string", help="mute the given id, so it stops being injected"),
            Flag(name="--expire", type="string", help="set the given id to expired"),
            Flag(name="--promote", type="string", help="move the given id to the host tier, so it is injected in every repo"),
            Flag(name="--demote", type="string", help="move the given id back from the host tier into this repo"),
            Flag(name="--generate-checks", type="bool", help="turn recognised instincts into `checks:` entries in a project recipe"),
            Flag(name="--recipe", type="string", default="bugfix", help="with --generate-checks: which project recipe to edit"),
            Flag(name="--step", type="string", help="with --generate-checks: which step to attach the checks to"),
            Flag(name="--min-confidence", type="float", help="with --generate-checks: floor on instinct confidence"),
            Flag(name="--dry-run", type="bool", help="with --generate-checks: report what would be written and stop"),
            Flag(name="--decay", type="bool", help="decay active instincts whose last_seen has not refreshed"),
            Flag(name="--inject-preview", type="bool", help="preview what would be injected at the next session start"),
            Flag(name="--json", type="bool", help="with --inject-preview: machine-readable output"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="the store was listed or changed"),
            ExitCode(code=1, meaning="rig refused the change — a candidate carrying a secret or a local path, or an id it does not hold"),
        ),
    ),
    Capability(
        id="wb.context",
        parent="wb",
        verb="context",
        intent="find out how much of the session's room to think rig's own output has been eating",
        preconditions=("git-repo",),
        effect_line=".rig/context.jsonl の計測から、rig の出力が親セッションの context をどれだけ消費したかを集計します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="--since-days", type="int", help="restrict to the last N days; all of them by default"),),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the measurement is shown"), _ERROR),
    ),
    Capability(
        id="wb.note",
        parent="wb",
        verb="note",
        intent="leave behind what this run learned, for whoever touches the same files next",
        preconditions=("git-repo", "task-exists"),
        effect_line="run 記録に申し送りを 1 件追記します（最大 2000 文字、--about で対象の相対パスを添えられます）",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="text", type="string", required=True, help="the note, at most 2000 characters"),
            Flag(name="--about", type="string-list",
                 help="a relative path inside the task the note is about, so a later run can open it (repeatable)"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the note is attached to the run"), _ERROR),
    ),
    Capability(
        id="wb.review",
        parent="wb",
        verb="review",
        intent="put on the record what each reviewer concluded, and the evidence they cited for it",
        preconditions=("git-repo", "task-exists", "review-body-readable"),
        effect_line="persona ごとの verdict を review.json に書き、--body を渡せばその本文を .rig/runs/<task>/reviews/<persona>.md に保存します",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--set", type="string-list", required=True,
                 help="PERSONA=VERDICT, one of APPROVE / REJECT / APPROVE_WITH_CONDITIONS (repeatable)"),
            Flag(name="--body", type="string-list",
                 help="PERSONA=@PATH: keep that reviewer's full text, and its file:line anchors (repeatable)"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the verdicts are recorded"), _ERROR),
    ),
    Capability(
        id="wb.confidence",
        parent="wb",
        verb="confidence",
        intent="find out how much a reviewer's approval is actually worth, from what they have been measured catching",
        preconditions=("git-repo", "drill-results-recorded", "review-verdicts-recorded"),
        effect_line="drill で実測した検出率から reviewer ごとの信頼度を示し、task を指定したときは acceptance.json にその値を書き込みます",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; without it, every persona measured so far"),
            Flag(name="--persona", type="string", help="reserved for a future single-persona lookup; currently unused"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the measured confidence is shown"), _ERROR),
    ),
    Capability(
        id="wb.gates",
        parent="wb",
        verb="gates",
        intent="find out what has to be true before work of this kind can be accepted here",
        preconditions=("none",),
        effect_line="acceptance gate の preset 定義と、この repository が足している criteria を表示します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="--json", type="bool", help="emit the presets as a rig.gates/v1 envelope"),),
        output_schema="rig.gates/v1",
        exit_codes=(ExitCode(code=0, meaning="the presets are shown"),),
    ),
    Capability(
        id="wb.drill-corpus",
        parent="wb",
        verb="drill-corpus",
        intent="find out whether the reviewers actually catch planted bugs, instead of trusting that they would",
        preconditions=("drill-corpus-available",),
        effect_line="materialize は使い捨ての git repo を指定ディレクトリに作り、score は採点行を --append 先の jsonl に追記します。--judge / calibrate-judge を使うと、判定内容が judge provider に送信されます（--judge-offline なら ledger だけで答え、送信しません）",
        effect_class="writes-worktree",
        network="sometimes",
        flags=(
            Flag(name="action", type="choice", required=True,
                 choices=("list", "materialize", "score", "calibrate-judge"),
                 help="list the cases, materialize one, score reviews against the answer key, or calibrate the judge"),
            Flag(name="case", type="string", help="with materialize: which case id"),
            Flag(name="--cases", type="string-list", help="restrict to these case ids; all of them by default"),
            Flag(name="--into", type="path", help="with materialize: target directory; a fresh temp dir by default"),
            Flag(name="--reviews", type="path", help="with score: JSON of {case-id: {persona: review text or @path}}"),
            Flag(name="--append", type="path", help="with score: append the scored row to this jsonl"),
            Flag(name="--judge", type="string",
                 help="with score: adjudicate each credited finding with this provider; without it the row yields no detection rate"),
            Flag(name="--judge-model", type="string", help="with --judge: which model the judge provider runs"),
            Flag(name="--judge-ledger", type="path", help="with --judge: JSONL of judge verdicts keyed by content hash, so a replay is deterministic"),
            Flag(name="--judge-offline", type="bool", help="with --judge-ledger: answer only from the ledger and never call a provider"),
            Flag(name="--workspace", type="string-list", help="CASE=DIR, so a reviewer's absolute file:line anchors resolve (repeatable)"),
            Flag(name="--json", type="bool", help="with list: machine-readable output"),
        ),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="the cases, the workspace path, the score row or the calibration is printed"),
            ExitCode(code=2, meaning="rig could not use the arguments — a --workspace that is not CASE=DIR"),
        ),
    ),
    Capability(
        id="wb.record-commit",
        parent="wb",
        verb="record-commit",
        intent="tie the commit that actually shipped back to the run that produced it",
        preconditions=("git-repo", "task-exists", "commit-exists"),
        effect_line="その task の記録に最終 commit の SHA を書き込みます（省略時は現在の HEAD）",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="sha", type="string", help="the commit; defaults to the current HEAD"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the commit is linked to the task"), _ERROR),
    ),
    Capability(
        id="wb.record-outcome",
        parent="wb",
        verb="record-outcome",
        intent="say plainly whether this change turned out fine or caused an incident once it was live",
        preconditions=("git-repo", "task-exists"),
        effect_line="その task の記録に ok / incident と任意の補足を書き込みます",
        effect_class="writes-state",
        network="never",
        flags=(
            Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),
            Flag(name="--status", type="choice", required=True, choices=("ok", "incident"),
                 help="what actually happened after this shipped"),
            Flag(name="--note", type="string", help="free-text detail"),
        ),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the outcome is recorded"), _ERROR),
    ),
    Capability(
        id="wb.trace-commit",
        parent="wb",
        verb="trace-commit",
        intent="find out where a commit came from and what was checked on it, starting from the SHA in a blame",
        preconditions=("git-repo", "commit-exists"),
        effect_line="commit SHA から、対応する task・gate が予測した内容・記録された結果を逆引きして表示します。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="sha", type="string", required=True, help="the commit SHA to look up"),),
        output_schema=None,
        exit_codes=(ExitCode(code=0, meaning="the commit was traced back to its task"), _ERROR),
    ),
    Capability(
        id="wb.verify-provenance",
        parent="wb",
        verb="verify-provenance",
        intent="find out whether the record of how this was accepted has been edited since it was written",
        preconditions=("git-repo", "task-exists", "provenance-record-exists"),
        effect_line="accept 時に署名された provenance 記録を、このマシンの鍵で照合します。第三者検証ではなく同一マシンでの改竄検知です。何も書き換えません",
        effect_class="read-only",
        network="never",
        flags=(Flag(name="task_id", type="string", help="the task; defaults to the one currently active"),),
        output_schema=None,
        exit_codes=(
            ExitCode(code=0, meaning="the signature matches the record"),
            ExitCode(code=1, meaning="the record does not match its signature — it was edited after the fact"),
            ExitCode(code=2, meaning="there is no provenance record to check; this task may not be accepted yet"),
        ),
    ),
)
